# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_component}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Peters"]
  s.date = %q{2011-01-03}
  s.description = %q{Active Component introduces components into your Rails presentation layer.
The use of components improves consistency and development speed through reuse and a new way of view code organization.
Components are plain Ruby classes that are able to render themselves using a to_html method.
Active Component provides several means that make it easy to write and use components.}
  s.email = %q{christian.peters@zweitag.de}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "active_component.gemspec",
    "init.rb",
    "lib/active_component.rb",
    "lib/active_component/base.rb",
    "lib/active_component/components/block.rb",
    "lib/active_component/components/empty_tag.rb",
    "lib/active_component/components/heading.rb",
    "lib/active_component/components/inline_tag.rb",
    "lib/active_component/components/section.rb",
    "lib/active_component/components/table.rb",
    "lib/active_component/config.rb",
    "lib/active_component/core_extensions.rb",
    "lib/active_component/template_handler.rb",
    "pkg/active_component-0.1.2.gem",
    "spec/active_component_spec.rb",
    "spec/active_component_spec_helper.rb",
    "spec/base_spec.rb",
    "spec/components/block_spec.rb",
    "spec/components/heading_spec.rb",
    "spec/components/section_spec.rb",
    "spec/components/table_spec.rb",
    "spec/core_extensions_spec.rb",
    "spec/factories.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ChristianPeters/activecomponent}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Build your views by assembling self-rendering components}
  s.test_files = [
    "spec/active_component_spec.rb",
    "spec/active_component_spec_helper.rb",
    "spec/base_spec.rb",
    "spec/components/block_spec.rb",
    "spec/components/heading_spec.rb",
    "spec/components/section_spec.rb",
    "spec/components/table_spec.rb",
    "spec/core_extensions_spec.rb",
    "spec/factories.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

